import {
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  BarChart,
  BarChart2,
  Bell,
  Calculator,
  CandlestickChart,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  DollarSign,
  Edit,
  Eye,
  EyeOff,
  FileCode,
  Home,
  Info,
  LineChart,
  Loader,
  Mail,
  MessageSquare,
  Minus,
  Moon,
  Play,
  Plus,
  Power,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Square,
  Sun,
  Trash,
  TrendingDown,
  TrendingUp,
  Twitter,
  UserPlus,
  Users,
  X
} from "lucide-react"

export const Icons = {
  alertTriangle: AlertTriangle,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  arrowRightLeft: ArrowRightLeft,
  arrowUp: ArrowUp,
  barChart: BarChart,
  barChart2: BarChart2,
  bell: Bell,
  calculator: Calculator,
  candlestickChart: CandlestickChart,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  close: X,
  dollarSign: DollarSign,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  fileCode: FileCode,
  home: Home,
  info: Info,
  lineChart: LineChart,
  loader: Loader,
  mail: Mail,
  messageSquare: MessageSquare,
  minus: Minus,
  moon: Moon,
  play: Play,
  plus: Plus,
  power: Power,
  reddit: MessageSquare, // Usando MessageSquare como sustituto para Reddit
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shield: Shield,
  stop: Square,
  sun: Sun,
  telegram: Mail, // Usando Mail como sustituto para Telegram
  trash: Trash,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  twitter: Twitter,
  userPlus: UserPlus,
  users: Users,
  x: X
}